// Auto-generated stub — will be regenerated by Plan 02 via:
//   npx supabase gen types typescript --linked > types/supabase.ts
//
// This stub allows lib/supabase/* to type-check before migrations exist.
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
